"""empty message

Revision ID: 0f25b49a6ff5
Revises: 
Create Date: 2024-06-01 22:22:05.331121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f25b49a6ff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('Ptype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_message_old_20240527')
    op.drop_table('_opencv_old_20240601_3')
    op.drop_table('_opencv_old_20240601_2')
    op.drop_table('_opencv_old_20240601_1')
    op.drop_table('_user_old_20240526')
    op.drop_table('_opencv_old_20240601_4')
    op.drop_table('_opencv_old_20240601_6')
    op.drop_table('_opencv_old_20240601')
    op.drop_table('_user_old_20240507_1')
    op.drop_table('_user_old_20240524')
    op.drop_table('_user_old_20240507')
    op.drop_table('_opencv_old_20240601_5')
    op.drop_table('_user_old_20240524_2')
    op.drop_table('_message_old_20240527_1')
    op.drop_table('_post_old_20240524')
    op.drop_table('_user_old_20240524_1')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('last_time',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('time',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Chat', ['chat_id'], ['id'])
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'User', ['sender'], ['id'])
        batch_op.create_foreign_key(None, 'User', ['receiver'], ['id'])
        batch_op.alter_column('last_time',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)

    op.create_table('_user_old_20240524_1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('senior', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_post_old_20240524',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('picture1', sa.VARCHAR(length=60), nullable=True),
    sa.Column('picture2', sa.VARCHAR(length=60), nullable=True),
    sa.Column('picture3', sa.VARCHAR(length=60), nullable=True),
    sa.Column('picture4', sa.VARCHAR(length=60), nullable=True),
    sa.Column('picture5', sa.VARCHAR(length=60), nullable=True),
    sa.Column('title', sa.VARCHAR(length=60), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('model', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_message_old_20240527_1',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=60), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_id', sa.INTEGER(), nullable=True),
    sa.Column('show_time', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['Chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_user_old_20240524_2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('senior', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601_5',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desciption', sa.TEXT(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_user_old_20240507',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('senior', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_user_old_20240524',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('senior', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_user_old_20240507_1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('senior', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601_6',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desciption', sa.TEXT(), nullable=True),
    sa.Column('image', sa.VARCHAR(length=60), nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601_4',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desciption', sa.TEXT(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_user_old_20240526',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.BOOLEAN(), nullable=True),
    sa.Column('senior', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601_1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desciption', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601_2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desciption', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_opencv_old_20240601_3',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desciption', sa.TEXT(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_message_old_20240527',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=60), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['Chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('picture')
    # ### end Alembic commands ###
